[package]
name = "rbinutils"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
"src/tc/*"
]

[dependencies]
strings = {optional = true, version = "*", package = "strings", path = "src/tc/strings"}

[[bin]]
name = "rbinutils"
path = "src/bin/rbinutils.rs"